env:
  num_node: 1
  node_ips: #the first item in the ip list is the master ip, pls make sure that the ip doesn't contain space in the end
    - 10.23.190.172
    # - 10.23.190.171
  tmp_path: /localdisk
  data_path: /data
  config_path: /localdisk/project/applications.ai.appliedml.workflow.analyticswithpython/applications/fraud_detection

data_preprocess:
  input_data_path: graph/input
  input_data_format: csv 
  output_data_path: graph/output
  output_data_format: csv
  dp_config_file: data-preprocessing.yaml 
  dp_framework: pandas

# training:
#   input_data_path: graph/output
#   input_data_format: csv 
#   train_config_file: model-training.yaml
#   train_framework: pandas
#   ray_params:
#     num_actors: 20
#     cpus_per_actor: 15 
#     elastic_training: True
#     max_failed_actors: 2
#     max_actor_restarts: 4
  
  


