files:
  data_path: /mnt/data/processed_data            # train and valid data path
  save_data_path: /mnt/data/processed4
  model_save_path: /mnt/tmp/models         # model saving path
  pred_save_path:  /mnt/tmp/result         # prediction result saving path
  hdfs_data_path: /recsys2021
  hdfs_model_path: /recsys2021/models
  hdfs_pred_path: /recsys2021/result

env:
  master: hadoop-master
  is_local: False

training:
  debug: False
  xgb4j_spark_jar: xgboost4j-spark_2.12-1.5.2.jar
  xgb4j_jar: xgboost4j_2.12-1.5.2.jar
