FROM python:3.8-buster
  
RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends openssh-server wget vim net-tools git-all htop && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
 
RUN ssh-keygen -t rsa -f /root/.ssh/id_rsa -P '' && \
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys && \
    sed -i 's/#   Port 22/Port 12345/' /etc/ssh/ssh_config && \
    sed -i 's/#Port 22/Port 12345/' /etc/ssh/sshd_config

RUN pip install --no-cache-dir numpy pandas sklearn transformers torch xgboost ray modin[ray] jupyter 

CMD ["sh", "-c", "service ssh start; bash"]
